### ISSUE TITLE
Dates in Quick Add

### ISSUE THREAD

**Issue by amazansky** [MyHomeworkSpace/client#133]
Most conventional date formats don't work in Quick Add (e.g. 5/11, may 11, etc.) More specifically:

- Quick Add recognizes **5/11/2020**, **5/11/2**, and **5/11/12345**, but sets the date to **5/11/2020** for all of those examples.
- It also recognizes 5/11/12asdf, but does not recognize the date on the regular add screen and just defaults to the current date.
- Same thing with month names—if you enter something like may 11, then it recognizes only the month "May" and leaves the 11 in the title. However, this only happens if you enter a number after the month, plus similarly to the previous example, it does not recognize the date as valid on the regular add screen and just defaults to the current date.

**Comment by thatoddmailbox** [comment]
Also the format 5-11 doesn't work. I'm not sure if it would be useful to ever type something like that normally though (e.g. "Read chapters 1-3") or if there's any good way of distinguishing that? I guess that's part of #132...

**Comment by thatoddmailbox** [comment]
@amazansky I think this should be fixed now? It's possible that I missed a test case/format though. It should be on staging2 (and eventually at some point on the live site) if you want to test.
