### ISSUE TITLE
Keyboard shortcut for all keyboard shortcuts

### ISSUE THREAD

**Issue by willbarkoff** [MyHomeworkSpace/client#136]
It would be nice if there were a keyboard shortcut (maybe <kbd>?</kbd>) to show all the keyboard shortcuts.

Gmail has a dialog to do this (they use the <kbd>?</kbd> shortcut)
<img width="1792" alt="Screen Shot 2020-04-27 at 12 48 10 PM" src="https://user-images.githubusercontent.com/10969136/80398377-83b61e80-8885-11ea-8955-e4790d670a3a.png">

**Comment by thatoddmailbox** [comment]
This was done in e327a06 but hasn't been pushed out yet, is it not working for you?

**Comment by willbarkoff** [comment]
Sorry I didn't see that this was done.
