### ISSUE TITLE
New name for Homework View

### ISSUE THREAD

**Issue by willbarkoff** [MyHomeworkSpace/client#137]
>Random thought: if we're putting calendar events on Homework view, it's not really much of a Homework view anymore, is it? Would we want to rename the tab to something like "Overview"? Or does that bring up too many memories of "Today is Tuesday, April 28, 2020"...

_Originally posted by @thatoddmailbox in https://github.com/MyHomeworkSpace/client/issues/131#issuecomment-620943375_

**Comment by thatoddmailbox** [comment]
Any suggestions for this? Two ideas:
![image](https://user-images.githubusercontent.com/1904587/80779213-f7338680-8b38-11ea-96e9-2987d162c876.png)
![image](https://user-images.githubusercontent.com/1904587/80779207-ec78f180-8b38-11ea-877c-d7e921b10969.png)

**Comment by willbarkoff** [comment]
I like "dashboard," I think the dial works well

**Comment by willbarkoff** [comment]
I'm going to ping @amazansky because he was active in the original discussion (https://github.com/MyHomeworkSpace/client/issues/131#issuecomment-620944445)

**Comment by amazansky** [comment]
I agree. I'd be fine with either, but dashboard is a cool name.
