### ISSUE TITLE
Issue/pull request templates

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/client#141]
None of us really use them, and they're somewhat rigid and verbose. Should we try to simplify/remove them?

**Comment by amazansky** [comment]
For issues, the solution seems like it would be to either add a blank template or remove/simplify what we already have. I think we should at least keep the template for User Feedback, though. It's good to standardize that stuff into one format. Thoughts? @thatoddmailbox @willbarkoff 

For PRs, the format seems fine as it's pretty short. Besides, we don't really use PRs within the MHS org, so it's good to keep it the way it is for outside contributors.

**Comment by thatoddmailbox** [comment]
I'm not totally convinced that GitHub is the right place for posting user feedback as-is. I feel like we should deal with that in Slack, and then if there's a request for features or bug fixes, we can make a specific issue here with whatever was requested. I guess we could add a label or something to say it's from feedback. Do you think it's important to preserve the exact wording of the feedback?

And yeah, for pull requests we could still have something for outside people, but I think some of that text needs to be updated. (the contribution guide links to a non-existent "join our team" page, and asks people filing issues to tell us the versions of Node and Jade they are using...)

**Comment by amazansky** [comment]
Yeah—those are fair points. For outside contributors, I think it'd be a good idea to keep some sort of format (maybe simpler), but update it to use our current stack.

Regarding user feedback, there's already a "user requested" label already, but I'm not really sure about whether we want to keep the user's wording or no. Dealing with small stuff in Slack before making an issue on GitHub also seems like a good idea so we only post user issues that we'd actually post here anyways.

**Comment by willbarkoff** [comment]
Ok, I made the issue templates a lot less rigid now they only have some reminders of what to include in your issues, and they add the right labels. The first one is also a "Blank" template, to start fresh

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/10969136/115793400-0d65d280-a39a-11eb-8fbd-a51481100e2e.png">

I think it's a good solution, but if anyone disagrees, feel free to reopen the issue.
