### ISSUE TITLE
Unauthenticated dummy MHS

### ISSUE THREAD

**Issue by amazansky** [MyHomeworkSpace/client#144]
**Describe the bug**: A user can view a dummy MyHomeworkSpace window without having authenticated. However, none of the buttons actually do anything, and anything that requires loading will just hang. (Sorry, I wasn't exactly sure what to title this issue 🙃)

**To Reproduce**
1. Go to https://app.myhomework.space (any implementation—dev, prod, local should all work)
2. Click create account button
3. Click the back button in your browser twice.

**Screenshots** (tested on Firefox, Chrome, Safari)

![image](https://user-images.githubusercontent.com/11902347/80854453-7cd13800-8c06-11ea-93ab-0256ce8e0d79.png)
![image](https://user-images.githubusercontent.com/11902347/80854461-91153500-8c06-11ea-8866-a4b3f5cdc172.png)

**Comment by willbarkoff** [comment]
I'm unable to reproduce this behavior on Firefox 76.0b8 or Safari 13.1 on macOS 10.15.4. Is anyone else able to reproduce it?

[Safari Test](https://1drv.ms/v/s!Ai88DA_vvTiyljk2bGzFt9u95-OL?e=9xmobY)
[Firefox Test](https://1drv.ms/v/s!Ai88DA_vvTiyljhWWKPg8bcPmeuL?e=dIo8rN)
