### ISSUE TITLE
Add homework modal doesn't autofocus title

### ISSUE THREAD

**Issue by willbarkoff** [MyHomeworkSpace/client#176]
Before the add homework modal redesign, the homework's title was autofocused. It now isn't. You could previously type the name of the assignment, then <kbd>enter</kbd> <kbd>enter</kbd> to submit. We stopped focusing on this once we started supporting <kbd>shift</kbd> + <kbd>enter</kbd> to add directly from quick add, but it should probably get fixed.

**Tracking**: Introduced in 49276917c567f6dc1fb28cd2c514bdda354ef827

**Comment by thatoddmailbox** [comment]
Closed in 01e9e1b59e08c012d1b7b0548a5714602884e93a
