### ISSUE TITLE
Websocket communications

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/client#22]
There should be a websockets connection established to the server. This would allow things like #21 to be live, and might maybe be faster for normal communications? (should test the speed, I'm not sure how much faster)

**Comment by thatoddmailbox** [comment]
The way I'm currently thinking about doing this is to have an API call (like /subscribe or something) that would return a websocket URL like wss://ws.myhomework.space and a ticket that it would use to connect to the websocket and identify as the user. (will that work? or maybe just use the session id from the cookie?) The different subdomain is required because of how IIS handles websocket sites (I think. I might be wrong though)

I'm also not sure if CloudFlare will work 100% with websockets. [They say that](https://support.cloudflare.com/hc/en-us/articles/200169466-Can-I-use-CloudFlare-with-websockets-) you can use websockets but there are unspecified soft limits on concurrent connections...

**Comment by willbarkoff** [comment]
I think we've determined that the time and effort required to do this aren't worth the benefits. If anyone wants to reopen, feel free to.
