### ISSUE TITLE
Internal

### ISSUE THREAD

**Issue by nywillb** [MyHomeworkSpace/client#24]
It would really be nice to have an internal panel like CoursesPlus. It should include these features:

- [ ] Announcements
- [ ] User Feedback
- [x] Statistics (Piwik)
- [x] Email
- [x] Blog
- [ ] Users

**Comment by thatoddmailbox** [comment]
So like https://internal.coursesplus.tk with user feedback?

**Comment by nywillb** [comment]
Yeah.

**Comment by nywillb** [comment]
Closing, because slack handles a lot of stuff like user feedback now, and we haven't really had a need for announcements. Statistics would be nice, so I opened #81.
