### ISSUE TITLE
Quick add abbreviations

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/client#28]
Quick add should understand abbreviations for classes. (for example, compsci -> Computer Science, chem -> Chemistry -> Science, etc) This might just be a hardcoded list, though we could expose it as an option for the user to change. (or maybe have a field when you edit the class?)

**Comment by nywillb** [comment]
Just a primitive list:

| Subject          	| Alternate Names                             	|
|------------------	|---------------------------------------------	|
| Science          	| Sci, Bio, Chem, Biology, Chemistry, Physics 	|
| Math             	| Algebra, Calc, Geometry, Geo                	|
| Computer Science 	| CompSci                                     	|
| Language         	| Mandarin, Spanish, Latin, French            	|
