### ISSUE TITLE
Quick add improvements

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/client#4]
Sentences that confuse it currently:
- Read day 1 for History next Tuesday
- take Quiz on things tomorrow in English class
- I have to read chapter 2 for French due tomorrow
- watch Science video for tomorrow

**Comment by thatoddmailbox** [comment]
Unprefixed entries are tricky to solve, since just having it use _all_ words would confuse it for sentences like "take Quiz on things tomorrow in English class" (it would include "take"). Maybe add more prefixes?

**Comment by nywillb** [comment]
![screen shot 2016-09-16 at 8 09 31 am](https://cloud.githubusercontent.com/assets/10969136/18585503/4c711a02-7be5-11e6-924a-bb46be89f287.png)

**Comment by nywillb** [comment]
Closing, because all the example phrases in this discussion currently work.
