### ISSUE TITLE
For the first 5 hours of a weekend, homework due Tuesday shows in the Monday column

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/client#48]
See title.

This is probably a timezone issue with UTC-5 on the client, but UTC on the server...

**Comment by nywillb** [comment]
@thatoddmailbox Can we just fix this buy setting the server time to UTC-5?

**Comment by RobotXLabs** [comment]
Or just switching it before it goes into MyHomeworkSpace?

*Sorry, I know I'm late, but **meh***

**Comment by nywillb** [comment]
Low priority because I don't think many people are doing homework between 12:00 AM and 5:00 AM on Friday night/Saturday morning.

**Comment by thatoddmailbox** [comment]
~how do you think this issue was found~
ok
