### ISSUE TITLE
Emojis in event title cause "internal server error"

### ISSUE THREAD

**Issue by nywillb** [MyHomeworkSpace/client#64]
![image](https://user-images.githubusercontent.com/10969136/30527104-dd981ba6-9bf2-11e7-8b16-7ca9f5ac796e.png)

@thatoddmailbox check the logs!

**Comment by RobotXLabs** [comment]
I feel the need to assign this high priority

**Comment by thatoddmailbox** [comment]
Fixed with MyHomeworkSpace/api-server@9ead299 and a database settings change.
