### ISSUE TITLE
Mg HCl Bug

### ISSUE THREAD

**Issue by medensqui** [MyHomeworkSpace/client#66]
Description: Whenever I type in any title/tag of a HW assignment, it switches to Report Mg HCl

Reproduction: Use my computer/account

Originality: Yes

Location: My computer, Chrome, live

Login: Yes. c19jf

**Comment by thatoddmailbox** [comment]
haha 060b7bd  didn't actually fix this

**Comment by thatoddmailbox** [comment]
@medensqui did this ever get fixed?

**Comment by nywillb** [comment]
I'm going to close since we haven't heard back. If anyone hears that this is still an issue, feel free to reopen.
