### ISSUE TITLE
Draggable modals

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/client#83]
Allow dragging modal dialogs around the screen, mainly useful for adding an event to the calendar (so you can see the events behind the dialog). This probably has to wait until all the modals are converted to preact, or else it could be confusing to have some draggable and some not.

**Comment by nywillb** [comment]
The only modal that still needs to be converted is the add/edit homework

**Comment by willbarkoff** [comment]
Why needs draggable modals when you can have _stretchy modals_?

![stretchy](https://user-images.githubusercontent.com/10969136/118007271-ffacc880-b319-11eb-89be-097f9189f486.gif)
