### ISSUE TITLE
Labs Section

### ISSUE THREAD

**Issue by willbarkoff** [MyHomeworkSpace/client#85]
### User Feedback
> Add a section where you can see your labs with teachers instead of it appearing as homework
#### User Type
> Student
#### Host
> Prod

**Comment by thatoddmailbox** [comment]
Isn't this just the calendar?

**Comment by nywillb** [comment]
I think what they mean is have a place where labs go automatically, basically an equivalent for homework view with labs

**Comment by thatoddmailbox** [comment]
Why though

**Comment by nywillb** [comment]
IDK.
