### ISSUE TITLE
Duplicate assignment creation from 

### ISSUE THREAD

**Issue by nywillb** [MyHomeworkSpace/client#96]
**Describe the bug**
Pressing return when creating an assignment from the planner creates two assignments.

**To Reproduce**
1. Open planner
2. Click on the "Add" button in any box
3. Type a name for the assignment
4. Press enter
5. Note that two assignments are created

**Expected behavior**
Only one assignment should be created

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox, Chrome
 - Version: Firefox 70.0b2, Chrome 76.0.3809.87

**Additional context**
The issue was reported by @c21lj - Thanks!

**Final Checklist**
Before submitting your issue, make sure you answer the following questions.

- [X] **Name**: Do you use a descriptive title to describe your issue? "It doesn't work," or "Fix HW View" are not detailed enough.
- [X] **Description**: Can you describe what was happening that caused you to report the issue? Was an error number displayed when you encountered the error? What was the error stack text?
- [X] **Reproduction**: Do steps need to be taken to reproduce this issue? If so, what steps?
- [X] **Originality**: Is this an original issue (make sure we haven't yet caught this on another issue)?
- [X] **Location**: Where can this issue be found? Is it on the live MyHomeworkSpace website or only on your local server? If running MyHomeworkSpace locally, what Node and Go versions do you have installed?
- [X] **Login**: Were you logged in when you found this error? If so, what is your username?

**Comment by thatoddmailbox** [comment]
Fixed in 10decdc

**Comment by nywillb** [comment]
Closed in 10decdce

**Comment by nywillb** [comment]
hmm it seems like there's a bit of a multithreading issue
